### ISSUE TITLE
Meal rotations are overlapping and non-sequentially numbered

### ISSUE THREAD

**Issue by stappon** [joyvuu-dave/comeals-rewrite#44]
Until recently, all rotations were non-overlapping and had sequential numbering. However, starting with Rotation 34, many rotations have one overlapping day, and the rotation numbers are incrementing by inconsistent intervals (34, 42, 44, 46, 48, 82)

**Comment by joyvuu-dave** [comment]
The overlap thing was due to time period end dates being inclusive. I think it was never noticed before because most meals have a day between them. I removed a minute from the end time and it fixed it. I'm less clear on why rotation intervals have started to skip numbers. Since rotation ids were just incremented in the database, I suspect there might have been something going on with my database instance. I replaced it, so we'll see if future rotation ids go back to incrementing by 1.
